CREATE DATABASE darklove
   USER SYS IDENTIFIED BY admin
   USER SYSTEM IDENTIFIED BY admin
   LOGFILE 
          GROUP 1 ('/u01/jvf40/logs/redo01a.log') SIZE 10M,
          GROUP 2 ('/u01/jvf40/logs/redo02a.log') SIZE 10M,
          GROUP 3 ('/u01/jvf40/logs/redo03a.log') SIZE 10M
   CHARACTER SET UTF8
   NATIONAL CHARACTER SET UTF8
   EXTENT MANAGEMENT LOCAL

   DATAFILE '/u01/jvf40/darklove/node03/oquti52.dbf' SIZE 100M REUSE AUTOEXTEND ON,
   '/u01/jvf40/darklove/node02/oziwo1.dbf' SIZE 100M REUSE AUTOEXTEND ON,
   '/u01/jvf40/darklove/node04/upito25.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED

   SYSAUX DATAFILE '/u01/jvf40/darklove/node01/gil4.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED

   DEFAULT TABLESPACE users
      DATAFILE '/u01/jvf40/darklove/node01/aliwohi567.dbf'
      SIZE 50M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED
   DEFAULT TEMPORARY TABLESPACE temp
   TEMPFILE '/u01/jvf40/darklove/temp01.dbf' SIZE 100M REUSE
   UNDO TABLESPACE undotbs1
   DATAFILE '/u01/jvf40/darklove/undotbs01.dbf' SIZE 100M REUSE 
   AUTOEXTEND ON MAXSIZE UNLIMITED;
